config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions
  resources :users
  resources :groups do
    member do
      post :remove_permission
    end
    resources :forms do
      resources :responses
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  root to: 'groups', action: 'index'

end

app/models/group.rb
class Group < ActiveRecord::Base

	belongs_to :owner, :class_name => 'User'
	belongs_to :parent, :class_name => 'Group'
	has_many :forms, -> { order name: :asc }
	has_many :subgroups, -> { order name: :asc }, foreign_key: :parent_id, :class_name => 'Group'

  has_many :permissions
	has_many :users, through: :permissions

  has_many :moderator_permissions, -> { where role_rank: 0 }, :class_name => 'Permission'
  has_many :moderators, source: :user, through: :moderator_permissions

  has_many :editor_permissions, -> { where role_rank: 1 }, :class_name => 'Permission'
  has_many :editors, source: :user, through: :editor_permissions

	before_create :set_supergroups

	def set_supergroups
		if parent
			group_index = parent.supergroups.max_by{ |k,v| v }.try(:last) || 0

			self.supergroups = parent.supergroups.merge({ "#{parent_id}" => group_index.to_i + 1 })
		else
			self.supergroups = {}
		end
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, except: [:index, :show]

  # GET /groups
  def index
    if logged_in?
      # The user's personal group (user_group) is the only group with both their ID, and a null group_id
      @user_group = Group.where(:owner_id => session[:user_id], :parent_id => [false, nil]).first! # First ensures a single record
      redirect_to :action => 'show', :id => @user_group.id
    else
      # If a user is not logged in, the Group index will show all user's personal groups.
      @top_level_groups = Group.where(:parent_id => [false, nil])
    end
  end

  # GET /groups/1
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
    @group.parent_id = params[:parent_id]
    @group.owner = @group.parent.owner
  end

  # GET /groups/1/edit
  def edit
    get_permission_variables
  end

  # POST /groups
  def create
    @group = Group.new(group_params)
    @group.parent_id = params[:parent_id]
    @group.owner = @group.parent.owner
    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /groups/1
  def update
    if (current_user == @group.owner)
      if !params[:new_editor_id].blank? then @group.permissions.create(:user_id => params[:new_editor_id], :group_id => @group.id, :role_rank => 1) end
      if !params[:new_moderator_id].blank? then @group.permissions.create(:user_id => params[:new_moderator_id], :group_id => @group.id, :role_rank => 0) end
    end
    get_permission_variables
    if @group.update(group_params)
      render :edit, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  def remove_permission
    @user = User.find(params[:remove_id])
    @group = Group.find(params[:id])
    @permission = Permission.where(:user => @user, :group => @group)
    @permission.destroy_all
    get_permission_variables
    render :edit
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def group_params
      params.require(:group).permit(:owner_id, :parent_id, :name, :permissions)
    end

    def get_permission_variables
      @moderators = @group.moderators
      @editors = @group.editors
      @users = User.all
      @users = @users.reject{ |r| @moderators.include? r }
      @users = @users.reject{ |r| @editors.include? r }
      @options = @users.map{ |u| [u.username, u.id] }
    end
end

app/helpers/groups_helper.rb
module GroupsHelper

end

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "Group Name:" %><br>
    <%= f.text_field :name %>
  </div>

  <table>
    <thead>
      <tr>
        <th>Moderators:</th>

        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @moderators.each do |moderator| %>
        <tr>
          <td><%= moderator.username %></td>
          <% if (@moderators.include? current_user) or current_user == @group.owner %>
            <td><%= link_to 'Remove', remove_permission_group_path(:remove_id => moderator.id), method: :delete_permission, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <% if (@group.moderators.include? current_user) or current_user == @group.owner %>
    <%= select_tag(:new_moderator_id, options_for_select(@options), :include_blank => true) %>
    <%# <%= link_to 'New Moderator (TODO)', new_group_form_path(:moderator_id => @group.id) %>
  <% end %>
  <p>================================</p>
  <br />
  <table>
    <thead>
      <tr>
        <th>Editors:</th>

        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @editors.each do |editor| %>
        <tr>
          <td><%= editor.username %></td>
          <% if (@moderators.include? current_user) or current_user == @group.owner %>
            <td><%= link_to 'Remove', remove_permission_group_path(:remove_id => editor.id, :group_id => @group.id), method: :delete_permission, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <% if (@moderators.include? current_user) or current_user == @group.owner %>
    <%= select_tag(:new_editor_id, options_for_select(@options), :include_blank => true) %>
    <%# link_to 'New Editor (TODO)', new_group_path(:parent_id => @group.id) %>
  <% end %>
  <br>
  <p>================================</p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', group_path(@group.id) %>

app/views/groups/index.html.erb
<table>
  <thead>
    <tr>
      <th>Top Level Groups</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @top_level_groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= link_to 'Show', group %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<p>================================</p>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= hidden_field_tag(:parent_id, @group.parent_id) %>
  <div class="field">
    <%= f.label "Group Name:" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', group_path(:id => @group.parent_id) %>

app/views/groups/show.html.erb
<% if @group.parent %>
  <%= link_to group_path(@group.parent), class: 'btn btn-sm btn-default' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back
  <% end %>
<% elsif not logged_in? %>
  <%= link_to groups_path, class: 'btn btn-sm btn-default' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back
  <% end %>
<% end %>

<% if can_edit? %>
  <%= link_to new_group_path(:parent_id => @group.id), class: 'btn btn-sm btn-default' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Add Subgroup
  <% end %>
  <%= link_to new_group_form_path(@group.id), class: 'btn btn-sm btn-default' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Add Form
  <% end %>

  <%= link_to edit_group_path(@group), class: 'btn btn-sm btn-default pull-right' do %>
    <span class="glyphicon glyphicon-cog"></span>
    Settings
  <% end %>
<% end %>

<div class="panel panel-default top7">
  <div class="panel-heading">
    <h1 class="panel-title"><%= @group.name %></h1>
  </div>
  <div class="panel-body list-group">
    <% @group.subgroups.each do |group| %>
      <%= link_to group, class: "list-group-item" do %>
        <span class="lead">
          <span class="glyphicon glyphicon-folder-close"></span>
          <%= group.name %>
        </span>
      <% end %>
    <% end %>
    <% @group.forms.each do |form| %>
      <%= link_to group_form_path(@group, form), class: "list-group-item" do %>
        <span class="lead">
          <span class="glyphicon glyphicon-list-alt"></span>
          <%= form.name %>
        </span>
      <% end %>
    <% end %>
  </div>
</div>