config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions
  resources :users
  resources :groups do
    member do
      post :remove_permission
    end
    resources :forms do
      resources :responses
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  root to: 'groups', action: 'index'

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  include HandlebarsSupport

  before_action :set_parents
  before_action :set_response, only: [:show, :edit, :update, :destroy]


  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @compiled = compile_template(@form.template)

    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new({
        form: @form,
        answers: params[:ans]
    })

    respond_to do |format|
      if @response.save
        format.html { redirect_to group_form_response_path(@group, @form, @response), notice: 'Response was successfully created.' }
        format.json { render :show, status: :created, location: @response }
      else
        format.html { render :new }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parents
      @group = Group.find params[:group_id]
      @form  = Form.find params[:form_id]
    end

    def set_response
      @response = Response.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:user_id, :answers, :form_id)
    end
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<h1>Listing responses</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Answers</th>
      <th>Form</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.user_id %></td>
        <td><%= response.answers %></td>
        <td><%= response.form_id %></td>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<%= link_to group_form_path(@group, @form), class: "btn btn-sm btn-default" do %>
  <span class="glyphicon glyphicon-chevron-left"></span>
  Back
<% end %>

<h1><%= @form.name %></h1>

<%= form_for [@group, @form, @response], html: {class: 'form'} do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= @compiled %>

  <div class="actions" data-bind="fadeVisible:display">
    <%= button_tag 'Submit', class: "btn btn-sm btn-default" %>
  </div>
<% end %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @response.respondent_id %>
</p>

<p>
  <strong>Answers:</strong>
  <%= @response.answers %>
</p>

<p>
  <strong>Form:</strong>
  <%= @response.form_id %>
</p>

<%= link_to 'Back', groups_path(@group) %>