config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions
  resources :users
  resources :groups do
    member do
      post :remove_permission
    end
    resources :forms do
      resources :responses
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  root to: 'groups', action: 'index'

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_group
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  # GET /forms
  def index
    @forms = Form.all
  end

  # GET /forms/1
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  def create
    @form = Form.new(form_params)
    @form.group = @group
    @form.owner = current_user

    unless can_edit?
      redirect_to group_url(@form.group), notice: "I'm sorry Dave, I can't let you do that."
    end

    if @form.save
      redirect_to [@form.group,@form], notice: 'Form was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /forms/1
  def update
    if @form.update(form_params)
      redirect_to [@group, @form], notice: 'Form was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /forms/1
  def destroy
    @form.destroy
    redirect_to group_url(@group), notice: 'Form was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:group_id])
    end

    def set_form
      @form = Form.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def form_params
      params.require(:form).permit(:owner_id, :group_id, :name, :template, :render_options)
    end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_for [@group, @form] do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label "Name" %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label "Template" %><br>
    <%= f.text_area :template, class: 'form-control code' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>
<%= link_to 'Back', @group %>

app/views/forms/edit.html.erb
<h1>Editing form</h1>

<%= render 'form' %>

app/views/forms/index.html.erb
<h1>Listing forms</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Group</th>
      <th>Name</th>
      <th>Template</th>
      <th>Render options</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= form.owner_id %></td>
        <td><%= form.group_id %></td>
        <td><%= form.name %></td>
        <td><%= form.template %></td>
        <td><%= form.render_options %></td>
        <td><%= link_to 'Show', form %></td>
        <td><%= link_to 'Edit', edit_form_path(form) %></td>
        <td><%= link_to 'Destroy', group_form_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Form', new_form_path %>

app/views/forms/new.html.erb
<h1>New form</h1>

<%= render 'form' %>

app/views/forms/show.html.erb
<%= form_for [@group, @form], html: { class: 'form-horizontal' } do |f| %>
  <%= link_to @group, class: 'btn btn-sm btn-default' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back
  <% end %>

  <div class="actions lock pull-right">
    <%= link_to 'Respond', new_group_form_response_path(@group, @form), class: 'btn btn-sm btn-default' %>

    <% if can_edit? %>
      <%= button_tag type: 'button', id: 'edit', class: 'btn btn-sm btn-default' do %>
        <span class="glyphicon glyphicon-edit"></span>
        Edit
      <% end %>
    <% end %>
  </div>

  <div class="actions edit hide pull-right">
    <% if can_edit? %>
      <%= button_tag type: 'button', id:'edit-cancel', class: 'btn btn-sm btn-default ' do %>
        <span class="glyphicon glyphicon-ban-circle"></span>
        Cancel
      <% end %>
      <%= button_tag class: 'btn btn-sm btn-default' do %>
        <span class="glyphicon glyphicon-save"></span>
        Save
      <% end %>
    <% end %>
  </div>

  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel panel-default top7">
    <div class="panel-heading">
      <div class="lock">
        <h1 class="panel-title"><%= @form.name %></h1>
      </div>
      <div class="has-feedback edit hide">
        <%= f.text_field :name, class: 'form-control' %>
        <span class="glyphicon glyphicon-edit form-control-feedback"></span>
      </div>
    </div>
    <div class="panel-body">
      <div class="lock">
        <pre><%= @form.template %></pre>
      </div>
      <div class="edit hide">
        <%= f.text_area :template, class: 'form-control code' %>
      </div>
    </div>
  </div>
<% end %>