config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions
  resources :users
  resources :groups do
    member do
      post :remove_permission
    end
    resources :forms do
      resources :responses
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  root to: 'groups', action: 'index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Formbuilder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "formbuilder", root_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <%= link_to_li "Groups", groups_path %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <%= link_to_li "Edit Profile", edit_user_path(current_user.id) %>
            <%= link_to_li "Logout", :logout, method: :post %>
          <% else %>
            <%= link_to_li "Register", new_user_path %>
            <%= link_to_li "Login", :login %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>
</body>
</html>